import torch
from matplotlib import pyplot as plt

if __name__ == '__main__':

    accuracies_model10 = torch.load("ex9_test_accuracy_1_128_0.pt")
    accuracies_model11 = torch.load("ex9_test_accuracy_1_128_1.pt")
    accuracies_model12 = torch.load("ex9_test_accuracy_1_128_2.pt")
    accuracies_model13 = torch.load("ex9_test_accuracy_1_128_3.pt")
    accuracies_combined1 = torch.load("ex9_combined_test_accuracy_1_128.pt")
    plt.plot(accuracies_model10, label="model 0, 1 layer with 128 neurons")
    plt.plot(accuracies_model11, label="model 1, 1 layer with 128 neurons")
    plt.plot(accuracies_model12, label="model 2, 1 layer with 128 neurons")
    plt.plot(accuracies_model13, label="model 3, 1 layer with 128 neurons")
    plt.plot(accuracies_combined1, label="combined model, 1 layer with 4*128 neurons")
    plt.legend()
    plt.xlabel("epochs")
    plt.ylabel("accuracies")
    plt.savefig("ex9_accuracies_1_128.png")
    plt.cla()

    accuracies_model50 = torch.load("ex9_test_accuracy_5_512_0.pt")
    accuracies_model51 = torch.load("ex9_test_accuracy_5_512_1.pt")
    accuracies_model52 = torch.load("ex9_test_accuracy_5_512_2.pt")
    accuracies_model53 = torch.load("ex9_test_accuracy_5_512_3.pt")
    accuracies_combined5 = torch.load("ex9_combined_test_accuracy_5_512.pt")
    plt.plot(accuracies_model50, label="model 0, 5 layers with 512 neurons")
    plt.plot(accuracies_model51, label="model 1, 5 layers with 512 neurons")
    plt.plot(accuracies_model52, label="model 2, 5 layers with 512 neurons")
    plt.plot(accuracies_model53, label="model 3, 5 layers with 512 neurons")
    plt.plot(accuracies_combined5, label="combined model, 5 layers with 4*512 neurons")
    plt.legend()
    plt.xlabel("epochs")
    plt.ylabel("accuracies")
    plt.savefig("ex9_accuracies_5_512.png")
    plt.cla()

    accuracies_model70 = torch.load("ex9_test_accuracy_7_64_0.pt")
    accuracies_model71 = torch.load("ex9_test_accuracy_7_64_1.pt")
    accuracies_model72 = torch.load("ex9_test_accuracy_7_64_2.pt")
    accuracies_model73 = torch.load("ex9_test_accuracy_7_64_3.pt")
    accuracies_combined7 = torch.load("ex9_combined_test_accuracy_7_64.pt")
    plt.plot(accuracies_model70, label="model 0, 7 layers with 64 neurons")
    plt.plot(accuracies_model71, label="model 1, 7 layers with 64 neurons")
    plt.plot(accuracies_model72, label="model 2, 7 layers with 64 neurons")
    plt.plot(accuracies_model73, label="model 3, 7 layers with 64 neurons")
    plt.plot(accuracies_combined7, label="combined model, 7 layers with 4*64 neurons")
    plt.legend()
    plt.xlabel("epochs")
    plt.ylabel("accuracies")
    plt.savefig("ex9_accuracies_7_64.png")
    plt.cla()
